services:
  database:
    container_name: database
    restart: on-failure:3
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - data:/var/lib/postgresql/data
      - dev-source-code:/app
    networks:
      - thingsboard

  model:
    container_name: model
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure:3
    environment:
      - WAIT_HOSTS=thingsboard_db:5432
      - AccountSid=${ACCOUNT_SID:-defaultSid}
      - AccountToken=${ACCOUNT_TOKEN:-defaultToken}
      - TwilioSmsFrom=${TWILIO_SMS_FROM:-+1234567890}
      - PhoneNumberID=${PHONE_NUMBER_ID:-123456789}
      - WB_TOKEN=${WB_TOKEN:-defaultWBToken}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS:-test@example.com}
      - APP_PASSWORD=${APP_PASSWORD:-defaultPassword}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://thingsboard:8080,http://thingsboard:4200}
      - MODELS_PATH=/app/models
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    build:
      context: ./predictive-maintenance
      dockerfile: .Dockerfile
    volumes:
      - dev-source-code:/app
      - models-data:/app/models
    networks:
      - thingsboard

  # Api Gateway
  thingsboard:
    container_name: thingsboard
    restart: on-failure:3
    ports:
      - "8080:8080"
      - "1883:1883"
      - "7071:7071"
      - "8883:8883"
    depends_on:
      database:
        condition: service_healthy
      model:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=database:5432,model:8000
      - FASTAPI_BASE_URL=http://model:8000/api/v1/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - dev-source-code:/app
      - m2-cache:/root/.m2
      - npm-cache:/root/.npm
      - gradle-cache:/root/.gradle
    networks:
      - thingsboard

  ui-ngx:
    container_name: thingsboard-ui
    restart: on-failure:3
    ports:
      - "4200:4200"
    depends_on:
      thingsboard:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=thingsboard:8080,model:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4200 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    build:
      context: ./ui-ngx
      dockerfile: .Dockerfile
    volumes:
      - dev-source-code:/app
      - npm-cache:/root/.npm
    networks:
      - thingsboard

  anomalies-script:
    container_name: anomalies-script
    depends_on:
      thingsboard:
        condition: service_healthy
    build:
      context: ./send-telemetry/
      dockerfile: anomalies-script.Dockerfile
    networks:
      - thingsboard

  forecast-script:
    container_name: forecast-script
    depends_on:
      thingsboard:
        condition: service_healthy
    build:
      context: ./send-telemetry/
      dockerfile: forecast-script.Dockerfile
    networks:
      - thingsboard

  ws-events:
    container_name: ws-events
    depends_on:
      thingsboard:
        condition: service_healthy
    build:
      context: ./send-telemetry/
      dockerfile: ws-events.Dockerfile
    networks:
      - thingsboard
    volumes:
      - dev-source-code:/app

  dashboard-script:
    container_name: dashboard-script
    depends_on:
      thingsboard:
        condition: service_healthy
    build:
      context: ./send-telemetry/
      dockerfile: dashboard-script.Dockerfile
    networks:
      - thingsboard

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../psql_data/main
  dev-source-code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .
  m2-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../thingsboard_m2_cache
  npm-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../thingsboard_npm_cache/
  gradle-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../thingsboard_gradle/
  models_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../thingsboard_models`

networks:
  thingsboard:
