services:
  postgres:
    image: postgres:16
    container_name: thingsboard_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - thingsboard
    env_file:
      - ./.env

  forecast-script:
    build:
      context: ./send-telemetry/
      dockerfile: forecast-script.Dockerfile
    container_name: forecast-script
    depends_on:
      - postgres
    networks:
      - thingsboard

  ws-events:
    build:
      context: ./send-telemetry/
      dockerfile: ws-events.Dockerfile
    container_name: ws-events
    depends_on:
      - postgres
    networks:
      - thingsboard
    volumes:
      - application_source_code:/app

  dashboard-script:
    build:
      context: ./send-telemetry/
      dockerfile: dashboard-script.Dockerfile
    container_name: dashboard-script
    depends_on:
      - postgres
    networks:
      - thingsboard

  fastapi:
    build:
      context: ./predictive-maintenance
      dockerfile: .Dockerfile
    container_name: fastapi
    restart: always
    volumes:
      - application_source_code:/app
    depends_on:
      - postgres
      - tb_application
    ports:
      - "8000:8000"
    # network_mode: host
    networks:
      - thingsboard

  tb_application:
    container_name: thingsboard
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - application_source_code:/app
      - application_m2_cache:/root/.m2
      - application_npm_cache:/root/.npm
      - application_gradle_cache:/root/.gradle
    # network_mode: host
    ports:
      - "8080:8080"
      - "1883:1883"
      - "7071:7071"
      - "8883:8883"
    networks:
      - thingsboard
    depends_on:
      - postgres

  ui-ngx:
    build:
      context: ui-ngx
      dockerfile: .Dockerfile
    container_name: thingsboard-dev
    volumes:
      - application_source_code:/app
      - application_npm_cache:/root/.npm
    # network_mode: host
    ports:
      - "4200:4200"
    networks:
      - thingsboard
    depends_on:
      - tb_application

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../psql_data/main
  application_source_code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .
  application_m2_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../thingsboard_m2_cache
  application_npm_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../thingsboard_npm_cache/
  application_gradle_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../thingsboard_gradle/

networks:
  thingsboard:
