version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: thingsboard_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thingsboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: ./predictive-maintenance
      dockerfile: .Dockerfile
    container_name: fastapi
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../psql_data/main/
