/**
 * Copyright © 2016-2024 The Thingsboard Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.server.dao.model;

import org.thingsboard.server.common.data.id.DeviceId;
import org.thingsboard.server.common.data.id.ModelLogId;
import org.thingsboard.server.common.data.id.TenantId;
import org.thingsboard.server.common.data.model.ModelLog;
import org.thingsboard.server.common.data.page.PageData;
import org.thingsboard.server.common.data.page.PageLink;

/**
 * Service for managing model logs.
 * Stores and retrieves logs generated by predictive maintenance models
 * (forecast and anomaly).
 */
public interface ModelLogService {

    /**
     * Save a new model log entry.
     *
     * @param tenantId the tenant ID
     * @param modelLog the log to save
     * @return the saved log with generated ID
     */
    ModelLog save(TenantId tenantId, ModelLog modelLog);

    /**
     * Find model logs within a time window with optional filtering.
     *
     * @param modelId  the model ID to filter by
     * @param startTs  start timestamp (milliseconds)
     * @param endTs    end timestamp (milliseconds)
     * @param logLevel optional log level filter (INFO, WARN, ERROR)
     * @param source   optional source filter (activation, ForecastModel,
     *                 AnomalyPredictor)
     * @param pageLink pagination parameters
     * @return page of model logs
     */
    PageData<ModelLog> findByModelIdAndTimeWindow(
            String modelId,
            Long startTs,
            Long endTs,
            String logLevel,
            String source,
            PageLink pageLink);

    /**
     * Count model logs matching the criteria.
     *
     * @param modelId  the model ID to filter by
     * @param startTs  start timestamp (milliseconds)
     * @param endTs    end timestamp (milliseconds)
     * @param logLevel optional log level filter
     * @param source   optional source filter
     * @return total count of matching logs
     */
    long countByModelIdAndTimeWindow(
            String modelId,
            Long startTs,
            Long endTs,
            String logLevel,
            String source);

    /**
     * Find a model log by ID.
     *
     * @param tenantId   the tenant ID
     * @param modelLogId the log ID
     * @return the model log or null if not found
     */
    ModelLog findById(TenantId tenantId, ModelLogId modelLogId);

    /**
     * Delete old model logs based on retention policy.
     *
     * @param retentionDays number of days to retain logs
     * @return number of deleted logs
     */
    int deleteOldLogs(int retentionDays);

    /**
     * Delete all logs for a specific model.
     *
     * @param modelId the model ID
     */
    void deleteByModelId(String modelId);

    /**
     * Find all logs for a tenant.
     *
     * @param tenantId the tenant ID
     * @param pageLink pagination parameters
     * @return page of model logs
     */
    PageData<ModelLog> findByTenantId(TenantId tenantId, PageLink pageLink);

    /**
     * Find all logs for a device.
     *
     * @param deviceId the device ID
     * @param pageLink pagination parameters
     * @return page of model logs
     */
    PageData<ModelLog> findByDeviceId(DeviceId deviceId, PageLink pageLink);
}
